version: 2

jobs:
  build:
    docker:
      - image: alpine:edge
    steps:
      - checkout
      - run: apk add git clang cmake build-base ninja autoconf automake libtool texinfo gettext-dev libexecinfo-dev gtest
      - run: git submodule update --init --recursive
      - run:
          name: make
          command: |
            mkdir build && \
            cd build && \
            CC=clang CXX=clang++ cmake -G Ninja .. && \
            ninja -j2
      - run:
          name: test
          command: ./build/test/jni-test
      - store_artifacts:
          path: build/libfake-jni.so
      - store_artifacts:
          path: build/examples/examples
      - store_artifacts:
          path: build/tests/tests
      - store_artifacts:
          path: include/fake-jni/

workflows:
  version: 2
  build:
   jobs:
    - build