version: 2

jobs:
  build:
    docker:
    - image: alpine:edge
    steps:
      - checkout
      - run: apk add git clang cmake build-base
      - run: git submodule update --init --recursive
      - run:
          name: make
          command: |
            mkdir build && \
            cd build && \
            CC=clang CXX=clang++ cmake .. && \
            make -j`nproc`
      - store_artifacts:
          path: build/examples/example
      - store_artifacts:
          path: build/tests/tests