version: 2

jobs:
  build:
    docker:
    - image: gcc:9.1.0
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y cmake
      - run:
          name: make
          command: |
            mkdir build && \
            cd build && \
            cmake .. && \
            make -j`nproc`
      - store_artifacts:
          path: build/examples/example

      - store_artifacts:
          path: build/tests/tests