version: 2

jobs:
  build:
    docker:
    - image: alpine:edge
    steps:
      - checkout
      - run: apk add git clang cmake build-base ninja autoconf automake libtool texinfo
      - run: git submodule update --init --recursive
      - run:
          name: make
          command: |
            mkdir build && \
            cd build && \
            CC=clang CXX=clang++ cmake -G Ninja .. && \
            cmake --build .
      - store_artifacts:
          path: build/libfake-jni.so
      - store_artifacts:
          path: build/examples/examples
      - store_artifacts:
          path: build/tests/tests
